name: "Build Dotnet with Pre-Download"

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Declare to use "actions/upload-artifact@v3" for pre-download
      - uses: actions/upload-artifact@v3
        continue-on-error: true

      - uses: actions/setup-dotnet@v2
        continue-on-error: true
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: ./Lottery/obj
          key: dotnet-${{ runner.os }}-${{ github.ref_name }}

      - uses: ./.github/composite/dotnet-build

      - uses: ./.github/composite/upload-artifact
        with:
          name: Lottery
          path: ./Lottery/bin/Release/net6.0

      - uses: actions/download-artifact@v3
        with:
          name: Lottery
          path: ./bin

      - name: List Artifact Files
        run: find ./bin/
